name: Build and Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}          # FTP server address
        username: ${{ secrets.FTP_USER }}          # FTP username
        password: ${{ secrets.FTP_PASS }}          # FTP password
        local-dir: './publish/'                    # Local directory to upload, ensure it ends with a /
        server-dir: '/htdocs/'         # Destination directory on the FTP server, ensure it ends with a /
        protocol: 'ftp'                            # Protocol (use 'sftp' for secure FTP)
