name: Build and Run .NET Application

on:
  push:
    branches:
      - main  # Change if your branch is different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Ensure this matches the .NET version you are using

    - name: Restore dependencies
      run: dotnet restore HelloWorldApp.csproj

    - name: Build the project
      run: dotnet build HelloWorldApp.csproj --configuration Release

    - name: Publish the .NET application
      run: dotnet publish HelloWorldApp.csproj --configuration Release --output ./publish

    - name: List files in the publish folder
      run: ls -al ./publish

    - name: Run the .NET application
      run: dotnet ./publish/HelloWorldApp.dll
