- name: Transfer Files to EC2
  uses: appleboy/scp-action@v0.1.1
  with:
    host: ${{ secrets.EC2_HOST }}           # EC2 public IP (stored as secret)
    username: ${{ secrets.EC2_USER }}       # EC2 user (usually 'ubuntu' for Ubuntu EC2)
    key: ${{ secrets.EC2_PEM_KEY }}         # PEM key stored in GitHub secrets
    source: ./publish/*                     # Files to transfer
    target: /var/www/dotnet-app             # Directory on EC2 to copy files
