name: Build and Run .NET Application

on:
  push:
    branches:
      - main  # Adjust if you're using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Match the .NET version used in the project

    - name: Restore dependencies
      run: dotnet restore DotNetDemo/DotNetDemo.csproj

    - name: Build the project
      run: dotnet build DotNetDemo/DotNetDemo.csproj --configuration Release

    - name: Publish the .NET application
      run: dotnet publish DotNetDemo/DotNetDemo.csproj --configuration Release --output ./publish

    - name: List files in the publish folder
      run: ls -al ./publish

    - name: Run the .NET application
      run: dotnet ./publish/DotNetDemo.dll
