name: Build and Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Copy to EC2 via SCP
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}         # EC2 instance IP
        username: ${{ secrets.EC2_USER }}     # Ubuntu user
        key: ${{ secrets.EC2_PEM_KEY }}       # PEM key
        source: './publish/*'                 # Path to your published app
        target: '/home/ubuntu/dotnet-app'     # Destination path on EC2
        port: 22                              # SSH port (default: 22)
        timeout: "30s"                        # Optional: Connection timeout
