name: Build and Publish .NET Core Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Use the version of .NET you need

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish .NET application
      run: |
        dotnet publish --configuration Release --output ./publish
        ls ./publish  # Verify that the files exist in the publish folder

    - name: Run the application
      run: dotnet ./publish/YourProjectName.dll  # Replace with your actual file name
